/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qltv;

import java.awt.BorderLayout;
import java.util.List;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSetMetaData;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author mai
 */
public final class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    
    protected Admin ad = null;
    
    public AdminForm(Admin ad) {
        initComponents();
        Soluong.setValue(-1);
        this.ad = ad;
        this.renderTableData(ad.GetAllSach());
        initializeUI();
        setLocationRelativeTo(null);
        setResizable(false);
        //setSize(1280, 800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        qlysach1 = new javax.swing.JButton();
        SachToTCN = new javax.swing.JButton();
        logout1 = new javax.swing.JButton();
        AdmintoMS = new javax.swing.JButton();
        SachToSV = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Images = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Masach = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Tensach = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Theloai = new javax.swing.JComboBox<>();
        Soluong = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        AddSach = new javax.swing.JButton();
        UpdateSach = new javax.swing.JButton();
        DeleteSach = new javax.swing.JButton();
        SearchSach = new javax.swing.JButton();
        ExitSach = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSach = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel9.setBackground(new java.awt.Color(255, 204, 204));
        jPanel9.setForeground(new java.awt.Color(255, 204, 204));

        jPanel10.setBackground(new java.awt.Color(255, 234, 234));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setForeground(new java.awt.Color(255, 153, 153));

        qlysach1.setBackground(new java.awt.Color(204, 204, 204));
        qlysach1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        qlysach1.setText("Quản Lý Sách");
        qlysach1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlysach1ActionPerformed(evt);
            }
        });

        SachToTCN.setBackground(new java.awt.Color(204, 204, 204));
        SachToTCN.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        SachToTCN.setText("Trang Cá Nhân");
        SachToTCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SachToTCNActionPerformed(evt);
            }
        });

        logout1.setBackground(new java.awt.Color(204, 204, 204));
        logout1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        logout1.setText("Logout");
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });

        AdmintoMS.setBackground(new java.awt.Color(204, 204, 204));
        AdmintoMS.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        AdmintoMS.setText("QL Mượn Sách");
        AdmintoMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmintoMSActionPerformed(evt);
            }
        });

        SachToSV.setBackground(new java.awt.Color(204, 204, 204));
        SachToSV.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SachToSV.setText("Quản Lý Sinh Viên");
        SachToSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SachToSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SachToTCN, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdmintoMS, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SachToSV, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qlysach1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(qlysach1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(SachToSV, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(AdmintoMS, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(SachToTCN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(logout1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        Images.setBackground(new java.awt.Color(250, 244, 240));
        Images.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel3.setText("Thể Loại");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Giáo trình");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Sách tham khảo");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Truyện");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Sách công nghệ_KHKT");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText(" Sách Khoa học-Xã Hội");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2005, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ImagesLayout = new javax.swing.GroupLayout(Images);
        Images.setLayout(ImagesLayout);
        ImagesLayout.setHorizontalGroup(
            ImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagesLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(ImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ImagesLayout.createSequentialGroup()
                        .addGroup(ImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ImagesLayout.createSequentialGroup()
                        .addGroup(ImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ImagesLayout.setVerticalGroup(
            ImagesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ImagesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addGap(41, 41, 41)
                .addComponent(jLabel8)
                .addGap(121, 121, 121)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(250, 244, 240));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel9.setText("Thông tin chi tiết");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Mã Sách");

        Masach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Thể Loại");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Tên Sách");

        Tensach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Tensach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TensachActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Số Lượng");

        Theloai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Theloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Giáo Trình", "Sách tham khảo", "Truyện", "Sách công nghệ_KHKT", "Sách khoa học xã hội", " " }));

        Soluong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Soluong.setName(""); // NOI18N
        Soluong.setRequestFocusEnabled(false);
        Soluong.setValue(-1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Masach)
                                .addComponent(Theloai, 0, 274, Short.MAX_VALUE)
                                .addComponent(Soluong))
                            .addComponent(Tensach, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Masach, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Tensach, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Theloai, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jPanel4.setBackground(new java.awt.Color(250, 244, 240));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AddSach.setBackground(new java.awt.Color(255, 204, 204));
        AddSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddSach.setText("Thêm");
        AddSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSachActionPerformed(evt);
            }
        });

        UpdateSach.setBackground(new java.awt.Color(255, 204, 204));
        UpdateSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UpdateSach.setText("Sửa");
        UpdateSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateSachActionPerformed(evt);
            }
        });

        DeleteSach.setBackground(new java.awt.Color(255, 204, 204));
        DeleteSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeleteSach.setText("Xóa");
        DeleteSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSachActionPerformed(evt);
            }
        });

        SearchSach.setBackground(new java.awt.Color(255, 204, 204));
        SearchSach.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        SearchSach.setText("Tìm Kiếm ");
        SearchSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchSachActionPerformed(evt);
            }
        });

        ExitSach.setBackground(new java.awt.Color(255, 204, 204));
        ExitSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ExitSach.setText("Thoát");
        ExitSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitSachActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel14.setText("Xử Lý");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExitSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(33, 33, 33)
                .addComponent(AddSach)
                .addGap(41, 41, 41)
                .addComponent(UpdateSach)
                .addGap(41, 41, 41)
                .addComponent(DeleteSach)
                .addGap(36, 36, 36)
                .addComponent(SearchSach)
                .addGap(47, 47, 47)
                .addComponent(ExitSach)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel15.setText("Bảng Thông tin");

        TableSach.setBackground(new java.awt.Color(250, 244, 240));
        TableSach.setToolTipText("");
        TableSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSach);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Images, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Images, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );

        jLabel2.setFont(new java.awt.Font("Georgia Pro", 2, 18)); // NOI18N
        jLabel2.setText("Thông tin sách");

        jPanel6.setBackground(new java.awt.Color(255, 240, 240));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("QUẢN LÝ SÁCH\n");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initializeUI(){
        ListSelectionModel selectionModel = TableSach.getSelectionModel();
        selectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        selectionModel.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(!e.getValueIsAdjusting()){
                    int selectedRow = TableSach.getSelectedRow();
                    if(selectedRow != -1){
                        Object idSach = TableSach.getValueAt(selectedRow, 0);
                        Object tenSach = TableSach.getValueAt(selectedRow, 1);
                        Object theLoai = TableSach.getValueAt(selectedRow, 2);
                        Object soLuong = TableSach.getValueAt(selectedRow, 3);
                        Masach.setText(idSach.toString());
                        Tensach.setText(tenSach.toString());
                        Theloai.setSelectedItem(theLoai.toString());
                        Soluong.setValue(Integer.parseInt(soLuong.toString()));
                    }
                }
            }
            
        });
    }
    
    private void TensachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TensachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TensachActionPerformed

    private void AddSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSachActionPerformed
        // TODO add your handling code here:
        if(this.CheckNull()){
            JOptionPane.showMessageDialog(null, "Nhập đầy đủ thông tin trước khi thêm");
            return;
        }
        if(this.ad.CheckMaSach(Masach.getText()) == 1){
            JOptionPane.showMessageDialog(null, "Mã sách đã tồn tại");
            return;
        }
        if(this.ad.AddSach(Tensach.getText(), (String) Theloai.getSelectedItem(), (int) Soluong.getValue(), Masach.getText()) == 1){
            JOptionPane.showMessageDialog(null, "Thêm Thành công");
            this.renderTableData(this.ad.GetAllSach());
            return;
        }else {
            JOptionPane.showMessageDialog(null, "Thêm thất bại");
            return;
        }
        
    }//GEN-LAST:event_AddSachActionPerformed

    private void SearchSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchSachActionPerformed
        // TODO add your handling code here:
        ConnectToSql conn = new ConnectToSql();
        ResultSet resultSet = null;
        try {
            StringBuilder queryBuilder = new StringBuilder("SELECT * FROM Sach WHERE 1 = 1");

            if (!Masach.getText().equals("")) {
                queryBuilder.append(" AND Masach like '%").append(Masach.getText()).append("%'");
            }

            if (!Tensach.getText().equals("")) {
                queryBuilder.append(" AND Tensach like '%").append(Tensach.getText()).append("%'");
            }

            if (!"Null".equals(Theloai.getSelectedItem())) {
                queryBuilder.append(" AND Theloai = '").append((String) Theloai.getSelectedItem()).append("'");
            }

            Object soLuongValue = Soluong.getValue();
            if (soLuongValue != null && Integer.parseInt(soLuongValue.toString()) > -1) {
                queryBuilder.append(" AND Soluong = ").append(Integer.parseInt(soLuongValue.toString()));
            }

            String querySql = queryBuilder.toString();
            System.out.println(querySql);
            conn.statement = conn.connection.prepareStatement(querySql);
            resultSet = conn.statement.executeQuery();
            this.renderTableData(resultSet);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_SearchSachActionPerformed

    private void TableSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSachMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TableSachMouseClicked

    private void UpdateSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateSachActionPerformed
        // TODO add your handling code here:
        if(Masach.getText().equals("") || this.CheckNull()){
            JOptionPane.showMessageDialog(null, "Nhập đầy đủ thông tin");
            return;
        }
        if(this.ad.UpdateSach(Masach.getText(), Tensach.getText(),(String) Theloai.getSelectedItem(),(int) Soluong.getValue()) == 1){
            JOptionPane.showMessageDialog(null, "Cập nhật thành công");
            this.renderTableData(this.ad.GetAllSach());
            return;
        }else{
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
            return;
        }
    }//GEN-LAST:event_UpdateSachActionPerformed

    private void DeleteSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSachActionPerformed
        // TODO add your handling code here:
        if(Masach.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Chọn sách cần xóa");
            return;
        }
        if(this.ad.CheckMaSach(Masach.getText()) == 0){
            JOptionPane.showMessageDialog(null, "Mã sách không tồn tại");
            return;
        }
        if(this.ad.DeleteSach(Masach.getText()) == 1){
            this.ad.DeleteMSWithMaSach(Masach.getText());
            JOptionPane.showMessageDialog(null, "Xóa thành công");
            Masach.setText("");
            Tensach.setText("");
            Theloai.setSelectedIndex(0);
            Soluong.setValue(-1);
            this.renderTableData(this.ad.GetAllSach());
            return;
        }else{
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
        }
    }//GEN-LAST:event_DeleteSachActionPerformed

    private void qlysach1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlysach1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qlysach1ActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Login lg = new Login();
        lg.setVisible(true);
        
    }//GEN-LAST:event_logout1ActionPerformed

    private void AdmintoMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmintoMSActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        QLMSForm qlms = new QLMSForm(this.ad);
        qlms.setVisible(true);
    }//GEN-LAST:event_AdmintoMSActionPerformed

    private void SachToSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SachToSVActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        QLSVForm qlsvFrom = new QLSVForm(this.ad);
        qlsvFrom.setVisible(true);
    }//GEN-LAST:event_SachToSVActionPerformed

    private void ExitSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitSachActionPerformed
        // TODO add your handling code here:
        Masach.setText("");
        Tensach.setText("");
        Theloai.setSelectedIndex(0);
        Soluong.setValue(-1);
        this.renderTableData(this.ad.GetAllSach());
    }//GEN-LAST:event_ExitSachActionPerformed

    private void SachToTCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SachToTCNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TrangCaNhan tcn = new TrangCaNhan(this.ad);
        tcn.setVisible(true);
    }//GEN-LAST:event_SachToTCNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            
        });
    }
    
    public void renderTableData(ResultSet resultSet) {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Mã Sách");
        tableModel.addColumn("Tên Sách");
        tableModel.addColumn("Thể Loại");
        tableModel.addColumn("Số Lượng");
        
        try {
            if (resultSet != null) {
                resultSet.beforeFirst();
                boolean hasData = false;
                while (resultSet.next()) {
                    hasData = true;
                    String maSach = resultSet.getString("Masach");
                    String tenSach = resultSet.getString("Tensach");
                    String theLoai = resultSet.getString("Theloai");
                    int soLuong = resultSet.getInt("Soluong");

                    Object[] rowData = {maSach, tenSach, theLoai, soLuong};
                    tableModel.addRow(rowData);
                }

                if (!hasData) {
                    JOptionPane.showMessageDialog(null, "Không có dữ liệu");
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        TableSach.setModel(tableModel);
    }
    
    public boolean CheckNull(){
        if (Masach.getText().equals("")) return true;
        if(Tensach.getText().equals("")) return true;
        if(Theloai.getSelectedIndex() == 0) return true;
        if(Soluong.getValue().equals("")) return true;
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSach;
    private javax.swing.JButton AdmintoMS;
    private javax.swing.JButton DeleteSach;
    private javax.swing.JButton ExitSach;
    private javax.swing.JPanel Images;
    private javax.swing.JTextField Masach;
    private javax.swing.JButton SachToSV;
    private javax.swing.JButton SachToTCN;
    private javax.swing.JButton SearchSach;
    private javax.swing.JSpinner Soluong;
    private javax.swing.JTable TableSach;
    private javax.swing.JTextField Tensach;
    private javax.swing.JComboBox<String> Theloai;
    private javax.swing.JButton UpdateSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout1;
    private javax.swing.JButton qlysach1;
    // End of variables declaration//GEN-END:variables


}
