/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qltv;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mai
 */
public class QLMSForm extends javax.swing.JFrame {

    /**
     * Creates new form QL_muon_sach
     */
    
    protected Admin ad;
    String Book;
    
    public QLMSForm(Admin ad) {
        initComponents();
        this.ad = ad;
        this.renderTableData(this.ad.GetAllMS());
        this.initializeUI();
        setLocationRelativeTo(null);
        setResizable(false);
        //setSize(1300, 890);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        MSToAd = new javax.swing.JButton();
        MSToTCN = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        qlmuonsach = new javax.swing.JButton();
        MStoSV = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MSTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        SachDaMuon = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        MasachSearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        TensachSearch = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TheloaiSearch = new javax.swing.JComboBox<>();
        Tong = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        SLMuon = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        ConlaiSearch = new javax.swing.JSpinner();
        SearchSach = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        AddMS = new javax.swing.JButton();
        UpdateMS = new javax.swing.JButton();
        DeleteMS = new javax.swing.JButton();
        SearchMS = new javax.swing.JButton();
        ExitMS = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        MaSV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Masach = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Soluong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Ngaymuon = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Ngayhentra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Tinhtrang = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Trasach = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        Mamuonsach = new javax.swing.JLabel();
        Ngaytra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel6.setBackground(new java.awt.Color(255, 222, 224));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, new java.awt.Color(204, 204, 204)));
        jPanel6.setForeground(new java.awt.Color(255, 153, 153));

        MSToAd.setBackground(new java.awt.Color(204, 204, 204));
        MSToAd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MSToAd.setText("Quản Lý Sách");
        MSToAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSToAdActionPerformed(evt);
            }
        });

        MSToTCN.setBackground(new java.awt.Color(204, 204, 204));
        MSToTCN.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        MSToTCN.setText("Trang Cá Nhân");
        MSToTCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MSToTCNActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(204, 204, 204));
        logout.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        qlmuonsach.setBackground(new java.awt.Color(204, 204, 204));
        qlmuonsach.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        qlmuonsach.setText("QL Mượn Sách");
        qlmuonsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qlmuonsachActionPerformed(evt);
            }
        });

        MStoSV.setBackground(new java.awt.Color(204, 204, 204));
        MStoSV.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MStoSV.setText("Quản Lý Sinh Viên");
        MStoSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MStoSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(qlmuonsach, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MSToTCN, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MStoSV, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MSToAd, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MSToAd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(MStoSV, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(qlmuonsach, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(MSToTCN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        MSTable.setBackground(new java.awt.Color(250, 244, 240));
        MSTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(MSTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("Thông tin sách");

        SachDaMuon.setBackground(new java.awt.Color(250, 244, 240));
        SachDaMuon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Mã Sách");

        MasachSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Thể Loại");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Tên Sách");

        TensachSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TensachSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TensachSearchActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Số Lượng");

        TheloaiSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TheloaiSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Đại cương", "Hacking", "Chuyên Ngành", "Sách tham khảo", "truyện", "Sách công nghệ_KHKT", "Sách khoa học xã hội" }));

        Tong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("SL Đã Mượn");

        SLMuon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Còn Lại");

        ConlaiSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        SearchSach.setBackground(new java.awt.Color(235, 144, 61));
        SearchSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SearchSach.setText("Tìm Kiếm ");
        SearchSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchSachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SachDaMuonLayout = new javax.swing.GroupLayout(SachDaMuon);
        SachDaMuon.setLayout(SachDaMuonLayout);
        SachDaMuonLayout.setHorizontalGroup(
            SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SachDaMuonLayout.createSequentialGroup()
                .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SachDaMuonLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel3)
                            .addGap(101, 101, 101)
                            .addComponent(ConlaiSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SachDaMuonLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel12)
                                .addComponent(jLabel10))
                            .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SachDaMuonLayout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TensachSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                        .addComponent(MasachSearch, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TheloaiSearch, 0, 0, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SachDaMuonLayout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Tong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SLMuon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(SachDaMuonLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel2)))
                    .addGroup(SachDaMuonLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(SearchSach)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SachDaMuonLayout.setVerticalGroup(
            SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SachDaMuonLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(MasachSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TensachSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SachDaMuonLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(TheloaiSearch)))
                .addGap(18, 18, 18)
                .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SLMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(SachDaMuonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConlaiSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchSach)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AddMS.setBackground(new java.awt.Color(255, 204, 204));
        AddMS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddMS.setText("Thêm");
        AddMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMSActionPerformed(evt);
            }
        });

        UpdateMS.setBackground(new java.awt.Color(255, 204, 204));
        UpdateMS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UpdateMS.setText("Sửa");
        UpdateMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateMSActionPerformed(evt);
            }
        });

        DeleteMS.setBackground(new java.awt.Color(255, 204, 204));
        DeleteMS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeleteMS.setText("Xóa");
        DeleteMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteMSActionPerformed(evt);
            }
        });

        SearchMS.setBackground(new java.awt.Color(255, 204, 204));
        SearchMS.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        SearchMS.setText("Tìm Kiếm ");
        SearchMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchMSActionPerformed(evt);
            }
        });

        ExitMS.setBackground(new java.awt.Color(255, 204, 204));
        ExitMS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ExitMS.setText("Thoát");
        ExitMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMSActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel14.setText("Xử Lý");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExitMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(33, 33, 33)
                .addComponent(AddMS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UpdateMS)
                .addGap(47, 47, 47)
                .addComponent(DeleteMS)
                .addGap(43, 43, 43)
                .addComponent(SearchMS)
                .addGap(46, 46, 46)
                .addComponent(ExitMS)
                .addGap(29, 29, 29))
        );

        jPanel3.setBackground(new java.awt.Color(250, 244, 240));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Mã Sinh Viên");

        MaSV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Mã Sách");

        Masach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Masach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasachActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Số Lượng Mượn");

        Soluong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Ngày Mượn");

        Ngaymuon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setText("Ngày Hẹn Trả");

        Ngayhentra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel16.setText("Ngày Trả");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel17.setText("Tình Trạng");

        Tinhtrang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Tinhtrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "Đã trả", "Chưa trả", " " }));

        jButton1.setBackground(new java.awt.Color(235, 144, 61));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("DS Sách Đã Mượn");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Trasach.setBackground(new java.awt.Color(235, 144, 61));
        Trasach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Trasach.setText("Trả sách");
        Trasach.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Trasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrasachActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("Mã Mượn Sách ");

        Mamuonsach.setBackground(new java.awt.Color(204, 204, 204));
        Mamuonsach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Mamuonsach.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Ngaytra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ngaytra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(Mamuonsach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(65, 65, 65)
                                .addComponent(Masach, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jButton1)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Ngayhentra))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Tinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Trasach, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ngaytra, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(69, 69, 69)
                                .addComponent(MaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Ngayhentra, Ngaymuon, Soluong});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Ngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(Mamuonsach, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ngayhentra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8)
                    .addComponent(Soluong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ngaytra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Masach, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(Tinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Trasach, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {MaSV, Mamuonsach, Masach, Ngaytra});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Ngayhentra, Ngaymuon, Soluong});

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setText("Thực hiện cho mượn");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel18.setText("Bảng Danh Sách");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1109, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel1)
                    .addGap(281, 281, 281)
                    .addComponent(jLabel4))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jLabel18))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(SachDaMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SachDaMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );

        jPanel7.setBackground(new java.awt.Color(255, 240, 240));

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("QUẢN LÝ MƯỢN SÁCH");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(458, 458, 458))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1364, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MSToAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSToAdActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminForm adminForm = new AdminForm(this.ad);
        adminForm.setVisible(true);
    }//GEN-LAST:event_MSToAdActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        this.setVisible(false);
        lg.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void qlmuonsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qlmuonsachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qlmuonsachActionPerformed

    private void MStoSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MStoSVActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        QLSVForm sv = new QLSVForm(this.ad);
        sv.setVisible(true);
    }//GEN-LAST:event_MStoSVActionPerformed

    private void TensachSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TensachSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TensachSearchActionPerformed

    private void AddMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMSActionPerformed
        // TODO add your handling code here:
        if(this.CheckNull()){
            JOptionPane.showMessageDialog(null, "Nhập đầy đủ thông tin");
            return;
        }
        if(this.ad.CheckMaSV(MaSV.getText()) == 0){
            JOptionPane.showMessageDialog(null, "Mã sinh viên không tồn tại");
            return;
        }
        if(this.ad.CheckMaSach(Masach.getText()) == 0){
            JOptionPane.showMessageDialog(null, "Mã sách không tồn tại");
            return;
        }
        if(this.ad.CheckSoLuongSach(Masach.getText(), Integer.parseInt(Soluong.getText())) == 1){
            JOptionPane.showMessageDialog(null, "Số lượng sách không đủ");
            return;
        }
        if (this.ad.AddMS(Masach.getText(), MaSV.getText(), Integer.parseInt(Soluong.getText()), Ngayhentra.getText()) == 1 && this.ad.UpdateSoLuongSach(Masach.getText(), Integer.parseInt(Soluong.getText())) == 1) {
            JOptionPane.showMessageDialog(null, "Thêm thành công");
            this.renderTableData(this.ad.GetAllMS());
            return;
        }else{
            JOptionPane.showMessageDialog(null, "Thêm thất bại");
            return;
        }
    }//GEN-LAST:event_AddMSActionPerformed

    private void SearchMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchMSActionPerformed
        // TODO add your handling code here:
        ConnectToSql conn = new ConnectToSql();
        ResultSet resultSet = null;
        try {
            StringBuilder queryBuilder = new StringBuilder("SELECT * FROM Muonsach WHERE 1 = 1");
            
            if(!Mamuonsach.getText().equals("")) {
                queryBuilder.append(" AND Mamuonsach = ").append(Mamuonsach.getText());
            }
            
            if(!Ngaymuon.getText().equals("")) {
                queryBuilder.append(" AND Ngaymuon like '%").append(Ngaymuon.getText()).append("%'");
            }
            
            if(!MaSV.getText().equals("")) {
                queryBuilder.append(" AND MaSV like '%").append(MaSV.getText()).append("%'");
            }
            
            if(!Ngayhentra.getText().equals("")) {
                queryBuilder.append(" AND Ngayhentra like '%").append(Ngayhentra.getText()).append("%'");
            }
            
            if(!Ngaytra.getText().equals("")){
                queryBuilder.append(" AND Ngaytra like '%").append(Ngaytra.getText()).append("%'");
            }
            
            if(!Soluong.getText().equals("")){
                queryBuilder.append(" AND Soluong = ").append(Soluong.getText());
            }
            
            if(!Masach.getText().equals("")){
                queryBuilder.append(" AND Masach like '%").append(Masach.getText()).append("%'");
            }
            
            if(!"Null".equals((String) Tinhtrang.getSelectedItem())){
                int temp = 0;
                String Trangthai = (String) Tinhtrang.getSelectedItem();
                if(Trangthai.equals("Đã Trả")){
                    temp = 1;
                }
                queryBuilder.append(" AND Tinhtrang = ").append(Integer.toString(temp));
            }
            
            String querySql = queryBuilder.toString();
            System.out.println(querySql);
            conn.statement = conn.connection.prepareStatement(querySql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            resultSet = conn.statement.executeQuery();
            if(resultSet.next()){
                this.renderTableData(resultSet);
            }else{
                JOptionPane.showMessageDialog(null, "Không có dữ liệu thỏa mãn");
            }
        } catch (Exception e) {
            e.printStackTrace(); // hoặc sử dụng Logger để ghi log
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_SearchMSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TrasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrasachActionPerformed
        // TODO add your handling code here:
        if(Mamuonsach.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Hãy chọn bạn đọc trả sách trước");
            return;
        }
        if(this.ad.GetTinhTrang(Integer.parseInt(Mamuonsach.getText())) == 1){
            JOptionPane.showMessageDialog(null, "Bản ghi bạn đã chọn đã trả sách");
            return;
        }
        String maSach = this.ad.GetMaSach((Integer.parseInt(Mamuonsach.getText())));
        int soLuongDangMuon = this.ad.GetSLOfMS(Integer.parseInt(Mamuonsach.getText()));
        int soLuongSachCon = this.ad.GetSoLuongSachCon(maSach);
        soLuongSachCon = soLuongSachCon + soLuongDangMuon;
        if(this.ad.UpdateSLSach(maSach, soLuongSachCon) == 1 && this.ad.Trasach(Integer.parseInt(Mamuonsach.getText())) == 1){
            JOptionPane.showMessageDialog(null, "Trả sách thành công");
            this.renderTableData(this.ad.GetAllMS());
            return;
        }else{
            JOptionPane.showMessageDialog(null, "Trả sách thất bại");
            return;
        }
        
    }//GEN-LAST:event_TrasachActionPerformed

    private void SearchSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchSachActionPerformed
        // TODO add your handling code here:
        ConnectToSql conn = new ConnectToSql();
        ResultSet result = null;
        try {
            StringBuilder queryBuldeStringBuilder = new StringBuilder("SELECT * FROM Sach WHERE 1 = 1");
            
            if(!MasachSearch.getText().equals("")){
                queryBuldeStringBuilder.append(" AND Masach = '").append(MasachSearch.getText()).append("'");
            }
            
            if(!TensachSearch.getText().equals("")){
                queryBuldeStringBuilder.append(" AND Tensach = '").append(TensachSearch.getText()).append("'");
            }
            
            if(!"Null".equals(TheloaiSearch.getSelectedItem())){
                queryBuldeStringBuilder.append(" AND Theloai = '").append(TheloaiSearch.getSelectedItem().toString()).append("'");
            }
            
            String querySql = queryBuldeStringBuilder.toString();
            conn.statement = conn.connection.prepareStatement(querySql);
            result = conn.statement.executeQuery();
            if(result.next()){
                MasachSearch.setText(result.getString("Masach"));
                TensachSearch.setText(result.getString("Tensach"));
                TheloaiSearch.setSelectedItem(result.getString("Theloai"));
                int Conlai = result.getInt("Soluong");
                ConlaiSearch.setValue(Conlai);
                int Muon = this.ad.GetSLSachMuon(MasachSearch.getText());
                SLMuon.setValue(Muon);
                Conlai = Conlai + Muon;
                Tong.setValue(Conlai);
            }else{
                JOptionPane.showMessageDialog(null, "Không có dữ liệu");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Không có dữ liệu");
            return;
        }
    }//GEN-LAST:event_SearchSachActionPerformed

    private void UpdateMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateMSActionPerformed
        // TODO add your handling code here:
        if (this.CheckNull()){
            JOptionPane.showMessageDialog(null, "Nhập đầy đủ thông tin");
            return;
        }
        if(Mamuonsach.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Hãy chọn bạn đọc trả sách trước");
            return;
        }
        if(this.ad.GetTinhTrang(Integer.parseInt(Mamuonsach.getText())) == 1){
            JOptionPane.showMessageDialog(null, "Bản ghi bạn đã chọn đã trả sách");
            return;
        }
        if(!Book.equals(Masach.getText())){
            if(this.ad.CheckSoLuongSach(Masach.getText(), Integer.parseInt(Soluong.getText())) == 1){
                JOptionPane.showMessageDialog(null, "Mã sách mới đổi không đủ số lượng");
                return;
            }
        }
        String maSach = this.ad.GetMaSach((Integer.parseInt(Mamuonsach.getText())));
        int soLuongDangMuon = this.ad.GetSLOfMS(Integer.parseInt(Mamuonsach.getText()));
        int soLuongSachCon = this.ad.GetSoLuongSachCon(maSach);
        soLuongSachCon = soLuongSachCon + soLuongDangMuon;
        if(soLuongSachCon < Integer.parseInt(Soluong.getText())){
            JOptionPane.showMessageDialog(null, "Số lượng sách còn tại không đủ");
            return;
        }
        if(this.ad.UpdateSLSach(maSach, soLuongSachCon) != 1){
            return;
        }
        if(this.ad.UpdateMS(Integer.parseInt(Mamuonsach.getText()), Masach.getText(), MaSV.getText(), Ngayhentra.getText(), Integer.parseInt(Soluong.getText())) == 1 && this.ad.UpdateSoLuongSach(Masach.getText(), Integer.parseInt(Soluong.getText())) == 1){
            JOptionPane.showMessageDialog(null, "Sửa thành công");
            this.renderTableData(this.ad.GetAllMS());
            return;
        }else{
            JOptionPane.showMessageDialog(null, "Sửa thất bại");
            return;
        }
    }//GEN-LAST:event_UpdateMSActionPerformed

    private void DeleteMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteMSActionPerformed
        // TODO add your handling code here:
        if(this.CheckNull() || Mamuonsach.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nhập đầy đủ thông tin");
            return;
        }
        int bit = 0;
        if(Tinhtrang.getSelectedIndex() == 1){
            bit = 1;
        }
        if (Tinhtrang.getSelectedIndex() == 2) {
            bit = 0;
        }
        if(bit == 1){
            if(this.ad.DeleteMS(Integer.parseInt(Mamuonsach.getText())) == 1){
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                this.renderTableData(this.ad.GetAllMS());
                return;
            }else{
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
                return;
            }
        }
        if(bit == 0){
            String Masachss = this.ad.GetMaSOfMS(Integer.parseInt(Mamuonsach.getText()));
            int Soluongcon = this.ad.GetSoLuongSachCon(Masachss);
            int Dangmuon = this.ad.GetSLOfMS(Integer.parseInt(Mamuonsach.getText()));
            Soluongcon = Soluongcon + Dangmuon;
            if(this.ad.UpdateSLSach(Masachss, Soluongcon) == 0){
                JOptionPane.showMessageDialog(null, "Có lỗi xảy ra");
                return;
            }
            if(this.ad.DeleteMS(Integer.parseInt(Mamuonsach.getText())) == 1){
                JOptionPane.showMessageDialog(null, "Xóa thành công");
                this.renderTableData(this.ad.GetAllMS());
                return;
            }else{
                JOptionPane.showMessageDialog(null, "Xóa thất bại");
                return;
            }
        }    
    }//GEN-LAST:event_DeleteMSActionPerformed

    private void ExitMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMSActionPerformed
        // TODO add your handling code here:
        Mamuonsach.setText("");
        Ngaymuon.setText("");
        MaSV.setText("");
        Ngayhentra.setText("");
        Ngaytra.setText("");
        Soluong.setText("");
        Masach.setText("");
        Tinhtrang.setSelectedIndex(0);
        this.renderTableData(this.ad.GetAllMS());
    }//GEN-LAST:event_ExitMSActionPerformed

    private void MSToTCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MSToTCNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TrangCaNhan tcn = new TrangCaNhan(this.ad);
        tcn.setVisible(true);
    }//GEN-LAST:event_MSToTCNActionPerformed

    private void MasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasachActionPerformed
    
    
    private void initializeUI(){
        ListSelectionModel selectionModel = MSTable.getSelectionModel();
        selectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        selectionModel.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(!e.getValueIsAdjusting()){
                    int selectedRow = MSTable.getSelectedRow();
                    if(selectedRow != -1){
                        Object mamuon = MSTable.getValueAt(selectedRow, 0);
                        Object masach = MSTable.getValueAt(selectedRow, 1);
                        Object masv = MSTable.getValueAt(selectedRow, 2);
                        Object soluong = MSTable.getValueAt(selectedRow, 3);
                        Object ngaymuon = MSTable.getValueAt(selectedRow, 4);
                        Object ngayhentra = MSTable.getValueAt(selectedRow, 5);
                        Object ngaytra = MSTable.getValueAt(selectedRow, 6);
                        Object tinhtrang = MSTable.getValueAt(selectedRow, 7);
                        Book = masach.toString();
                        Mamuonsach.setText(mamuon.toString());
                        Ngaymuon.setText(ngaymuon.toString());
                        MaSV.setText(masv.toString());
                        Ngayhentra.setText(ngayhentra.toString());
                        Soluong.setText(soluong.toString());
                        Masach.setText(masach.toString());
                        Tinhtrang.setSelectedItem(tinhtrang.toString());
                        if(ngaytra != null){
                            Ngaytra.setText(ngaytra.toString());
                        }else{
                            Ngaytra.setText("");
                        }
                    }
                }
            }
            
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLMSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLMSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLMSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLMSForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            
        });
    }
    
    public void renderTableData(ResultSet resultSet) {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Mã Mượn");
        tableModel.addColumn("Mã sách");
        tableModel.addColumn("Mã sinh viên");
        tableModel.addColumn("Số lượng");
        tableModel.addColumn("Ngày mượn");
        tableModel.addColumn("Ngày hẹn trả");
        tableModel.addColumn("Ngày trả");
        tableModel.addColumn("Tình trạng");
        
        try {
            if (resultSet != null) {
                resultSet.beforeFirst();
                boolean hasData = false;
                while (resultSet.next()) {
                    hasData = true;
                    int mamuon = resultSet.getInt("Mamuonsach");
                    String idsach = resultSet.getString("Masach");
                    String maSv = resultSet.getString("MaSV");
                    int soluong = resultSet.getInt("Soluong");
                    String ngaymuon = resultSet.getString("Ngaymuon");
                    String ngayhentra = resultSet.getString("Ngayhentra");
                    String ngaytra = resultSet.getString("Ngaytra");
                    String tinhtrang = (resultSet.getInt("Tinhtrang") == 0) ? "Chưa trả" : "Đã trả";

                    Object[] rowData = {mamuon, idsach, maSv, soluong, ngaymuon, ngayhentra, ngaytra, tinhtrang};
                    tableModel.addRow(rowData);
                }

                if (!hasData) {
                    JOptionPane.showMessageDialog(null, "Không có dữ liệu");
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        MSTable.setModel(tableModel);
    }
    
    public boolean CheckNull(){
        if(Soluong.getText().equals("")) return true;
        if(MaSV.getText().equals("")) return true;
        if(Ngayhentra.getText().equals("")) return true;
        if(Integer.parseInt(Soluong.getText()) == 0) return true;
        if(Masach.getText().equals("")) return true;
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddMS;
    private javax.swing.JSpinner ConlaiSearch;
    private javax.swing.JButton DeleteMS;
    private javax.swing.JButton ExitMS;
    private javax.swing.JTable MSTable;
    private javax.swing.JButton MSToAd;
    private javax.swing.JButton MSToTCN;
    private javax.swing.JButton MStoSV;
    private javax.swing.JTextField MaSV;
    private javax.swing.JLabel Mamuonsach;
    private javax.swing.JTextField Masach;
    private javax.swing.JTextField MasachSearch;
    private javax.swing.JTextField Ngayhentra;
    private javax.swing.JTextField Ngaymuon;
    private javax.swing.JLabel Ngaytra;
    private javax.swing.JSpinner SLMuon;
    private javax.swing.JPanel SachDaMuon;
    private javax.swing.JButton SearchMS;
    private javax.swing.JButton SearchSach;
    private javax.swing.JTextField Soluong;
    private javax.swing.JTextField TensachSearch;
    private javax.swing.JComboBox<String> TheloaiSearch;
    private javax.swing.JComboBox<String> Tinhtrang;
    private javax.swing.JSpinner Tong;
    private javax.swing.JButton Trasach;
    private javax.swing.JButton UpdateMS;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    private javax.swing.JButton qlmuonsach;
    // End of variables declaration//GEN-END:variables
}
