/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qltv;

import java.security.MessageDigest;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mai
 */
public class QLSVForm
        extends javax.swing.JFrame {

    /**
     * Creates new form Them_sach
     */
    
    protected Admin ad = null;
    String temp = "";
    
    public QLSVForm(Admin ad) {
        initComponents();
        this.ad = ad;
        this.renderTableData(this.ad.GetAllUsers());
        initializeUI();
        setLocationRelativeTo(null);
        setResizable(false);
         //setSize(1300, 890);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        SVToSach = new javax.swing.JButton();
        TrangCaNhan = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        SVtoMS = new javax.swing.JButton();
        QLSVToTCN = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        AddUsser = new javax.swing.JButton();
        UpdateUser = new javax.swing.JButton();
        DeleteUser = new javax.swing.JButton();
        SearchUser = new javax.swing.JButton();
        ExitUser = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MaSV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Hoten = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Nam = new javax.swing.JRadioButton();
        Nu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Lop = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Khoa = new javax.swing.JComboBox<>();
        Ngaysinh = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        Level = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBackground(new java.awt.Color(255, 234, 234));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, new java.awt.Color(204, 204, 204)));
        jPanel6.setForeground(new java.awt.Color(255, 153, 153));

        SVToSach.setBackground(new java.awt.Color(204, 204, 204));
        SVToSach.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SVToSach.setText("Quản Lý Sách");
        SVToSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SVToSachActionPerformed(evt);
            }
        });

        TrangCaNhan.setBackground(new java.awt.Color(204, 204, 204));
        TrangCaNhan.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        TrangCaNhan.setText("Trang Cá Nhân");
        TrangCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrangCaNhanActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(204, 204, 204));
        logout.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        SVtoMS.setBackground(new java.awt.Color(204, 204, 204));
        SVtoMS.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        SVtoMS.setText("QL Mượn Sách");
        SVtoMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SVtoMSActionPerformed(evt);
            }
        });

        QLSVToTCN.setBackground(new java.awt.Color(204, 204, 204));
        QLSVToTCN.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        QLSVToTCN.setText("Quản Lý Sinh Viên");
        QLSVToTCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QLSVToTCNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TrangCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SVtoMS, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QLSVToTCN, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SVToSach, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(SVToSach, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(QLSVToTCN, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(SVtoMS, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(TrangCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jPanel4.setBackground(new java.awt.Color(250, 244, 240));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AddUsser.setBackground(new java.awt.Color(255, 204, 204));
        AddUsser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddUsser.setText("Thêm");
        AddUsser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUsserActionPerformed(evt);
            }
        });

        UpdateUser.setBackground(new java.awt.Color(255, 204, 204));
        UpdateUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        UpdateUser.setText("Sửa");
        UpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserActionPerformed(evt);
            }
        });

        DeleteUser.setBackground(new java.awt.Color(255, 204, 204));
        DeleteUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DeleteUser.setText("Xóa");
        DeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserActionPerformed(evt);
            }
        });

        SearchUser.setBackground(new java.awt.Color(255, 204, 204));
        SearchUser.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        SearchUser.setText("Tìm Kiếm ");
        SearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchUserActionPerformed(evt);
            }
        });

        ExitUser.setBackground(new java.awt.Color(255, 204, 204));
        ExitUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ExitUser.setText("Thoát");
        ExitUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitUserActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        jLabel14.setText("Xử Lý");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExitUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddUsser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addComponent(AddUsser)
                .addGap(29, 29, 29)
                .addComponent(UpdateUser)
                .addGap(27, 27, 27)
                .addComponent(DeleteUser)
                .addGap(29, 29, 29)
                .addComponent(SearchUser)
                .addGap(29, 29, 29)
                .addComponent(ExitUser)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("USERNAME");

        MaSV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        MaSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaSVActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Họ Và Tên");

        Hoten.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Giới tính");

        buttonGroup1.add(Nam);
        Nam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nam.setText("Nam");
        Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamActionPerformed(evt);
            }
        });

        buttonGroup1.add(Nu);
        Nu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nu.setText("Nữ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Ngày Sinh");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Lớp");

        Lop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Khoa");

        Khoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Khoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "An Toàn Thông Tin", "Công Nghệ Thông Tin", "Điện Tử Viễn Thông", " " }));

        Ngaysinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Level");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("PassWord");

        Password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        Level.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Null", "0", "1" }));

        jLabel12.setBackground(new java.awt.Color(51, 51, 51));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4))))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hoten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Nam)
                        .addGap(30, 30, 30)
                        .addComponent(Nu))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Level, 0, 219, Short.MAX_VALUE)
                        .addComponent(MaSV)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lop, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(Level, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lop, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nu)
                        .addComponent(Nam)
                        .addComponent(jLabel5)
                        .addComponent(Khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 51, 0));
        jLabel9.setText("Bảng thông tin");

        UserTable.setBackground(new java.awt.Color(250, 244, 240));
        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        UserTable.setToolTipText("");
        jScrollPane1.setViewportView(UserTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Thông tin sinh viên");

        jPanel7.setBackground(new java.awt.Color(255, 240, 240));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SVToSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SVToSachActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        AdminForm adminForm = new AdminForm(this.ad);
        adminForm.setVisible(true);
    }//GEN-LAST:event_SVToSachActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        this.setVisible(false);
        lg.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void SVtoMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SVtoMSActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        QLMSForm qlms = new QLMSForm(this.ad);
        qlms.setVisible(true);
    }//GEN-LAST:event_SVtoMSActionPerformed

    private void QLSVToTCNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QLSVToTCNActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TrangCaNhan tcn = new TrangCaNhan(this.ad);
        tcn.setVisible(true);
    }//GEN-LAST:event_QLSVToTCNActionPerformed

    private void NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamActionPerformed

    private void MaSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaSVActionPerformed

    private void SearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchUserActionPerformed
        // TODO add your handling code here:
        ConnectToSql conn = new ConnectToSql();
        ResultSet resultSet = null;
        try {
            StringBuilder queryBuilder = new StringBuilder("SELECT * FROM Users WHERE 1 = 1");

            if (!MaSV.getText().equals("")) {
                queryBuilder.append(" AND MaSV like '%").append(MaSV.getText()).append("%'");
            }

            if (!Hoten.getText().equals("")) {
                queryBuilder.append(" AND Hoten like '%").append(Hoten.getText()).append("%'");
            }
            
            if(!Ngaysinh.getText().equals("")){
                queryBuilder.append(" AND Ngaysinh like '%").append(Ngaysinh.getText()).append("%'");
            }
            
            if(Nam.isSelected() || Nu.isSelected()){
                String Text = Nam.isSelected() ? "Nam" : "Nữ";
                queryBuilder.append(" AND Gioitinh = N'").append(Text).append("'");
            }
            
            if(!Lop.getText().equals("")){
                queryBuilder.append(" AND Lop like '%").append(Lop.getText()).append("%'");
            }
            
            if(!"Null".equals((String) Khoa.getSelectedItem())){
                queryBuilder.append(" AND Khoa = '").append((String) Khoa.getSelectedItem()).append("'");
            }

            if(!"Null".equals((String) Level.getSelectedItem())){
                queryBuilder.append(" AND Level = ").append((String) Level.getSelectedItem());
            }
            
            String querySql = queryBuilder.toString();
            System.out.println(querySql);
            conn.statement = conn.connection.prepareStatement(querySql, ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            resultSet = conn.statement.executeQuery();
            if(resultSet.next()){
                this.renderTableData(resultSet);
            }else{
                JOptionPane.showMessageDialog(null, "Không có dữ liệu thỏa mãn");
            }
        } catch (Exception e) {
            e.printStackTrace(); // hoặc sử dụng Logger để ghi log
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_SearchUserActionPerformed

    private void AddUsserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUsserActionPerformed
        // TODO add your handling code here:
        if(this.CheckNull()){
            JOptionPane.showMessageDialog(null, "Nhập đầy đủ thông tin");
            return;
        }
        if(this.CheckMaSV()){
            JOptionPane.showMessageDialog(null, "Mã sinh viên đã tồn tại");
            return;
        }
        if(!this.ad.isValidDateFormat(Ngaysinh.getText(), "dd-mm-yyy")){
            JOptionPane.showMessageDialog(null, "Ngày sinh theo định dạng dd-mm-yyyy");
            return;
        }
        char[] CharPass = Password.getPassword();
        String Pass = new String(CharPass);
        Arrays.fill(CharPass, ' ');
        if(Pass.equals("")){
            JOptionPane.showMessageDialog(null, "Nhập đầy đủ thông tin");
            return;
        }
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] PasswordByte = Pass.getBytes();
            byte[] PasswordHash = md.digest(PasswordByte);
            StringBuilder hexString = new StringBuilder();
            for (byte b : PasswordHash) {
                String hex = String.format("%02x", b);
                hexString.append(hex);
            }
            if(this.ad.AddUsers(MaSV.getText(), hexString.toString(), Hoten.getText(), Nam.isSelected() ? "Nam" : "Nữ", Ngaysinh.getText(), Lop.getText(), (String) Khoa.getSelectedItem(), Integer.parseInt((String) Level.getSelectedItem())) == 1){
                JOptionPane.showMessageDialog(null, "Thêm thành công");
                this.renderTableData(this.ad.GetAllUsers());
                return;
            }else{
                JOptionPane.showMessageDialog(null, "Thêm thất bại");
                return;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e);
            return;
        }
    }//GEN-LAST:event_AddUsserActionPerformed
    
    private void initializeUI(){
        ListSelectionModel selectionModel = UserTable.getSelectionModel();
        selectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        selectionModel.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(!e.getValueIsAdjusting()){
                    int selectedRow = UserTable.getSelectedRow();
                    if(selectedRow != -1){
                        Object maSV = UserTable.getValueAt(selectedRow, 0);
                        Object hoTen = UserTable.getValueAt(selectedRow, 1);
                        Object ngaySinh = UserTable.getValueAt(selectedRow, 2);
                        Object gioiTinh = UserTable.getValueAt(selectedRow, 3);
                        Object lop = UserTable.getValueAt(selectedRow, 4);
                        Object khoa = UserTable.getValueAt(selectedRow, 5);
                        Object level = UserTable.getValueAt(selectedRow, 6);
                        MaSV.setText(maSV.toString());
                        temp = maSV.toString();
                        Hoten.setText(hoTen.toString());
                        Ngaysinh.setText(ngaySinh.toString());
                        if(gioiTinh.toString().equals("Nam")){
                            Nam.setSelected(true);
                        }else{
                            Nu.setSelected(true);
                        }
                        Lop.setText(lop.toString());
                        Khoa.setSelectedItem(khoa.toString());
                        Level.setSelectedItem(level.toString());
                    }
                }
            }
            
        });
    }
    
    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void UpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUserActionPerformed
        // TODO add your handling code here:
        if(this.CheckNull()){
            JOptionPane.showMessageDialog(null, "Nhập đầy đủ thông tin");
            return;
        }
        if(!temp.equals(MaSV.getText())){
            JOptionPane.showMessageDialog(null, "Bạn không được thay đổi mã sinh viên");
            return;
        }
        char[] CharPass = Password.getPassword();
        String Pass = new String(CharPass);
        Arrays.fill(CharPass, ' ');
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] PasswordByte = Pass.getBytes();
            byte[] PasswordHash = md.digest(PasswordByte);
            StringBuilder hexString = new StringBuilder();
            for (byte b : PasswordHash) {
                String hex = String.format("%02x", b);
                hexString.append(hex);
            }
            int check = 0;
            if(Pass.equals("")){
                if(this.ad.UpdateUsers(MaSV.getText(), Hoten.getText(), Nam.isSelected() ? "Nam" : "Nữ", Ngaysinh.getText(), Lop.getText(), (String) Khoa.getSelectedItem(), Integer.parseInt((String) Level.getSelectedItem())) == 1){
                    check = 1;
                }
            }else{
                if(this.ad.UpdateUsers(MaSV.getText(), Hoten.getText(), Nam.isSelected() ? "Nam" : "Nữ", Ngaysinh.getText(), Lop.getText(), (String) Khoa.getSelectedItem(), Integer.parseInt((String) Level.getSelectedItem())) == 1 && this.ad.UpdatePassword(MaSV.getText(), hexString.toString()) == 1){
                    check = 1;
                }
            }
            if(check == 1){
                JOptionPane.showMessageDialog(null, "Sửa thành công");
                this.renderTableData(this.ad.GetAllUsers());
                return;
            }else{
                JOptionPane.showMessageDialog(null, "Sửa thất bại");
                return;
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_UpdateUserActionPerformed

    private void DeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserActionPerformed
        // TODO add your handling code here:
        if(MaSV.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Chọn sinh viên để xóa");
            return;
        }
        if(!this.CheckMaSV()){
            JOptionPane.showMessageDialog(null, "Mã sinh viên không tồn tại");
            return;
        }
        if(MaSV.getText().equals(this.ad.getMaSV())){
            JOptionPane.showMessageDialog(null, "Bạn không thể tự xóa chính mình");
            return;
        }
        if(this.ad.DeleteUsers(MaSV.getText()) == 1){
            this.ad.DeleteMSWithMaSV(MaSV.getText());
            JOptionPane.showMessageDialog(null, "Xóa thành công");
            this.renderTableData(this.ad.GetAllUsers());
            return;
        }else{
            JOptionPane.showMessageDialog(null, "Xóa thất bại");
            return;
        }
    }//GEN-LAST:event_DeleteUserActionPerformed

    private void ExitUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitUserActionPerformed
        // TODO add your handling code here:
        MaSV.setText("");
        Password.setText("");
        Level.setSelectedIndex(0);
        Hoten.setText("");
        Ngaysinh.setText("");
        Lop.setText("");
        Nam.setSelected(false);
        Nu.setSelected(false);
        Khoa.setSelectedIndex(0);
        this.renderTableData(this.ad.GetAllUsers());
    }//GEN-LAST:event_ExitUserActionPerformed

    private void TrangCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrangCaNhanActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TrangCaNhan tcn = new TrangCaNhan(this.ad);
        tcn.setVisible(true);
    }//GEN-LAST:event_TrangCaNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
            }
        });
    }
    
    public void renderTableData(ResultSet resultSet) {
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.addColumn("Mã SV");
        tableModel.addColumn("Họ Tên");
        tableModel.addColumn("Ngày Sinh");
        tableModel.addColumn("Giới Tính");
        tableModel.addColumn("Lớp");
        tableModel.addColumn("Khoa");
        tableModel.addColumn("Level");
        
        try {
            if (resultSet != null) {
                resultSet.beforeFirst();
                boolean hasData = false;
                while (resultSet.next()) {
                    hasData = true;
                    String maSV = resultSet.getString("MaSV");
                    String hoTen = resultSet.getString("Hoten");
                    String ngaySinh = resultSet.getString("Ngaysinh");
                    String gioiTinh = resultSet.getString("Gioitinh");
                    String lop = resultSet.getString("Lop");
                    String khoa = resultSet.getString("Khoa");
                    int level = resultSet.getInt("Level");

                    Object[] rowData = {maSV, hoTen, ngaySinh, gioiTinh, lop, khoa, level};
                    tableModel.addRow(rowData);
                }

                if (!hasData) {
                    JOptionPane.showMessageDialog(null, "Không có dữ liệu");
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        UserTable.setModel(tableModel);
    }
    
    public boolean CheckNull(){
        if(Level.getSelectedIndex() == 0) return true;
        if(MaSV.getText().equals("")) return true;
        if(Ngaysinh.getText().equals("")) return true;
        if(Hoten.getText().equals("")) return true;
        if(Lop.getText().equals("")) return true;
        if(!Nam.isSelected() && !Nu.isSelected()) return true;
        if("Null".equals(Khoa.getSelectedItem())) return true;
        return false;
    }
    
    public boolean CheckMaSV(){
        if(this.ad.CheckMaSV(MaSV.getText()) == 1) return true;
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUsser;
    private javax.swing.JButton DeleteUser;
    private javax.swing.JButton ExitUser;
    private javax.swing.JTextField Hoten;
    private javax.swing.JComboBox<String> Khoa;
    private javax.swing.JComboBox<String> Level;
    private javax.swing.JTextField Lop;
    private javax.swing.JTextField MaSV;
    private javax.swing.JRadioButton Nam;
    private javax.swing.JTextField Ngaysinh;
    private javax.swing.JRadioButton Nu;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton QLSVToTCN;
    private javax.swing.JButton SVToSach;
    private javax.swing.JButton SVtoMS;
    private javax.swing.JButton SearchUser;
    private javax.swing.JButton TrangCaNhan;
    private javax.swing.JButton UpdateUser;
    private javax.swing.JTable UserTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
